sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.6" COVERAGE="true" DEPLOY_DOCS="1"

git:
  depth: 3

branches:
  only:
  - master
  - develop

install:
  - source ci_scripts/travis_install.sh

script:
  - source ci_scripts/travis_test.sh

after_success:
  - source ci_scripts/travis_success.sh
  - bash ci_scripts/deploy_docs.sh

notifications:
  email: false